### PR TITLE
Update index.d.ts to include properties added by props

### PR DESCRIPTION
**Pull request by gbishop**
As discussed in issue #4, I am suggesting that `T` (the type of `props`) should be added to the properties of the final class.

### CODE REVIEW

**Comment by ArthurClemens** [comment]
I do see problems when using the element in other libraries, for example React.

Let's say you have a component wrapper around `<my-button>`:
```ts
const MyCounter = (props: MyCounterProps) => (
  <my-counter {...props}></my-counter>
);
```
where `MyCounterProps` is defined in the CE:

```ts
/**
 * Attributes passed to the component:
 * `<my-counter></my-counter>`
 * `<my-counter count="10"></my-counter>`
 */
export type MyCounterProps = {
  count?: number;
};
```

`count` is optional - you can omit the "count" property and just write `<my-counter>`.

But the causes problems: inside the `init` function `this.count` is now an optional number, and can't be used for calculations.

See [an example where this happens](https://codesandbox.io/s/uce-with-react-and-typescript-test-types-263k8?file=/src/uceElements/MyCounter.ts).

I think it is clearer to have external props ("public interface") separated from internal (private) state. That way you can always change the internal handling of passed props without making changes to the public interface.

**Comment by gbishop** [comment]
That is a reasonable decision for a designer to make but the change I propose doesn't prevent you from making that design decision. It simply makes the types correspond to the way the define function actually works. 

Your example code should work unchanged with my changes to types.

**Comment by ArthurClemens** [comment]
I've [updated the example code](https://codesandbox.io/s/uce-with-react-and-typescript-test-types-263k8?file=/src/uceElements/MyCounter.ts) to show that the problem remains.

This time the props contain an optional string. This is how the example should have been, since HTML element props are strings:

```ts
export type MyCounterProps = {
  count?: string;
};
```

Several scenarios trying to to mitigate the problem:
1. If I leave out `count` from `OwnProps` (as you suggest), `this.count` will be `string | undefined` and cannot be used for calculations
1. If I keep `count` in `OwnProps` (my code), `this.count` has type `never`
1. Forcing the type doesn't work either (adding `this.count = ( .... ) as number`)
1. I could resort to create a new variable in `OwnProps`, e.g. `_count`, but this is worse

The problem is that outside props and internal state a conflated, and that does not work out well in this - not farfetched - example.

**Comment by gbishop** [comment]
I agree with your analysis but shouldn't the types describe what uce actually does? The types as currently defined do not describe the actual behaviour of the `define` function. 
The `define` function sets things up so the properties named in the `props` member get added to the class at the top level. I don't think type-checked users should be denied that functionality if they choose to use it.

**Comment by ArthurClemens** [comment]
I suggest to only change line 104 to:

```ts
props?: Partial<U> | null;
```

(`U` being the OwnProps generic)

This works fine with
```ts

type Props = unknown;

type OwnProps = {
  count: number;
  inc: () => unknown;
  dec: () => unknown;
  default: string;
  other: number;
};

...

export const MyCounter: IMyCounter = {
  props: {
    default: '99',
    other: 100
  },
  init: function () {
     ...
```

and

```ts
type Props = unknown;

type OwnProps = {
  count: number;
  inc: () => unknown;
  dec: () => unknown;
}

export const MyCounter: IMyCounter = {
  props: {
    count: 99
  },
  init: function () {
     ...
```
a well as supporting `props: null`.

**Comment by gbishop** [comment]
So `T` is unused? I'll have to try this later. Too late to think now.

**Comment by WebReflection** [comment]
Sorry folks, I am a bit confused ... should we change anything in here?

**Comment by gbishop** [comment]
I closed the pull request. I've put more time into it and I should already.
No need for a change, I'm moving on.

**Comment by ArthurClemens** [comment]
It makes sense to change the definition of `props` in define. I'll make a separate PR.

**Pull request closed without merging**
